menu:
- {name: 'Home', url: '/'}
- {name: 'CV', <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3140400" target="_blank" rel="noreferrer noopener" aria-label=" (opens in a new tab)" style="text-decoration:none;>}
